remote_theme: chesterhow/tale
title: just push buttons

permalink:    /:year-:month-:day/:title
paginate:     15

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
